### ISSUE TITLE
Reliability Question and Connection Problem

### ISSUE THREAD

**Issue by stefanpoeter** [roccomuso/node-ads#1]
Hi @roccomuso,

I am thinking about using your module to talk to a Beckhoff PLC. Do you use this module yourself and is it considered to be stable? 

I tried to connect to TwinCAT3 on my Virtual Machine but wasn't very successfull. Wireshark said the connection was established successfully. I also added a project route and set the amsPortTarget to 851 (due to TwinCAT3) but no luck. I always experience a timeout in the error handler.

**Comment by roccomuso** [comment]
I did a few tests and generally speaking, it works. But I do not consider the module "stable".
This repo was an attempt to recover old ads code found in a couple of forks around.

Bug fixes are welcome.

**Comment by stefanpoeter** [comment]
I'll see if I can get it to work and if so, I'll make some patches. Repository Access would be good :-)

**Comment by roccomuso** [comment]
ok, cool, feel free to open a PR

**Comment by sanderd17** [comment]
I also had issues connecting to TC3. It appears that the default port changed from 801 to 851 with TC3 (and that setting is quite well hidden).

Perhaps that could be added to some documentation here.

**Comment by roccomuso** [comment]
@sanderd17 Could you open a PR to better document this? thx

**Comment by Wolfskammer04** [comment]
Hello @roccomuso ,
I use a CX5020 for my trials and also have problems to connect. I tried a several times different combinations of Adresses NetIds and ports but no success. Here are the error messages I face:
"Error ADS: Error: connect ECONNREFUSED 192.168.137.235:48898"
"Error readDeviceInfo: timeout"
"Ads Register Notification live tick timeout"
"Ads Register Notification Sym Tab timeout"

the ECONNREFUSED message sometimes dissappears suddenly but also suddenly comes back without having made any config changes.

**Comment by roccomuso** [comment]
@Wolfskammer04 Consider opening a [new issue](https://github.com/roccomuso/node-ads/issues/new) to address the problem.

**Comment by ChrisHanuta** [comment]
@Wolfskammer04 
**Configuration**

Enable ADS on your PLC project. To do this click on your task and then enable the checkbox before Create symbols (if he is not disabled). In addition, you can still, under I/O Devices 

- click on Image and go to the ADS tab. Check the Enable ADS Server and also Create symbols. Download the new configuration and make sure you reboot your PLC. The reboot is only needed when you are using TwinCat 2.

- **Now add a static route to our Beckhoff PLC**. The route should point to your server that will run the proxy application. It's also a good idea to add an extra static route that points to your local development device. This way you can test out the proxy from your development device too.

**Attention**

- TwinCAT AMS Router doesn't allow multiple TCP connections from the same host. So when you use two AdsLib instances on the same host to connect to the same TwinCAT router, you will see that TwinCAT will close the first TCP connection and only respond to the newest. **If you start the TwinCat System Manager and Node-Red ADS on the same PC at the same time, Node-Red will not run anymore.** You can set up a second IPv4 on the PC and assign to this a ADS NET ID under Twincat

- As ADS is transmitted over a TCP connection, there is no real time guarantee.

**Comment by ChrisHanuta** [comment]
@roccomuso I think we can close this one. The port is in the readme....
