### ISSUE TITLE
Occasional "Symbol not found"

### ISSUE THREAD

**Issue by acidos** [roccomuso/node-ads#19]
I have an app which is periodically writing few variables in PLC. The period is every 5 minute.
```
var options = {
    host: "127.0.0.1",
    amsNetIdTarget: "10.10.2.100.1.1",
    amsNetIdSource: "10.10.2.100.1.15",
    amsPortTarget: 801
}

var client = ads.connect(options, function() {
                    WriteAds(client, values[0]).
                    then(() => WriteAds(client, values[1])).
                    then(() => WriteAds(client, values[2])).
                    then(() => WriteAds(client, values[3])).
                    then(() => WriteAds(client, values[4])).
                    then(() => WriteAds(client, values[5])).
                    then(() => WriteAds(client, values[6])).
                    then(() => WriteAds(client, validityHandle)).
                    catch((err) => { 
                        log.error("Error writing to ADS: ", err);
                    }).
                    finally(() => ReleaseAndDisconnect(client))
                })

function ReleaseAndDisconnect(client)
{
    return new Promise(function(resolve, reject){
        client.end(function (){ resolve() })
        resolve()
    })
}

function WriteAds(client, h)
{
    return new Promise(function(resolve, reject){
        client.write(h, function(err) {
            if (err) 
            {
                reject(err)
            }
            else
            {
                resolve()
            }
        })
    })
}


```

As you can see, there are 6 handles in array and 1 standalone handle. This is the exception

```
Error writing to ADS: symbol not found
Error: symbol not found
    at getError (C:\pkg\node_modules\node-ads\lib\ads.js:1290:13)
    at Object.getWriteResult (C:\pkg\node_modules\node-ads\lib\ads.js:792:13)
    at Object.analyseResponse (C:\pkg\node_modules\node-ads\lib\ads.js:224:24)
    at Object.checkResponseStream (C:\pkg\node_modules\node-ads\lib\ads.js:177:25)
    at Socket.<anonymous> (C:\pkg\node_modules\node-ads\lib\ads.js:116:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
```
It happens on standalone variable. Variables before are written just fine.

I captured ADS traffic and can see that `ADSIGRP_SYM_HNDBYNAME` is called for all variables following `ADSIGRP_SYM_VALBYHND`, except last one. The last one only received `ADSIGRP_SYM_VALBYHND` without prior `ADSIGRP_SYM_HNDBYNAME`. Not sure where index/offset was discovered, but there is some value. Is it cached somewhere?

**Comment by ChrisHanuta** [comment]
Global symname must start with a dot: `.engine`, program symname must start with the programname: `MAIN.UpTyp.timerUp.PT`.

There is also a problem with special characters, because node-ads pass the texts as UTF8 to the PLC and not as ASCII. Do you want to tell us the symname name?

You can use getSymbols to trace the known names.

```
client = ads.connect(options, function() {
    this.getSymbols(function(err, symbols) {
        if (err) console.log(err)
        console.log(symbols)
        this.end()
    })
})
```

**Comment by acidos** [comment]
This is the failing handle

```
var validityHandle = {
    symname: 'MAIN.PKG.bEnable',
    bytelength: ads.BOOL,  
    propname: 'value',
    value: true
}
```
The successful ones are `MAIN.PKG.BLA_BLA` matching exactly to the ones declared in PLC. The type of others are mixed, including float, bool, though I don't think it's related. As I stated, the error "symbol not found" happens occasionally, but with some pattern. If I just start my node app, first(or first few) times everything is successful. The program is running on `setInterval` of 5 minutes. On consequent timer events, the exception occurs.

**Comment by acidos** [comment]
> better you remove the second resolve() ;-)

ah, dankeschön :)

**Comment by acidos** [comment]
So what I tried is moved `then(() => WriteAds(client, validityHandle)).` to the top, to see if the failure is related to the last Write, but it failed again on exactly this handle. If something wrong with the name of the handle, why it's writing successfully always very first time?

**Comment by ChrisHanuta** [comment]
I think the second resolve() is not the problem here.

I am puzzled about: 
> _The last one only received ADSIGRP_SYM_VALBYHND without prior ADSIGRP_SYM_HNDBYNAME._

node-ads has a peculiarity, it writes all information into the transferred object. ADSIGRP_SYM_HNDBYNAME is not called when a handle is handed over. But then the symname is forbidden

**Comment by acidos** [comment]
So I have bunch of ADSIGRP_SYM_HNDBYNAME calls like below for all handles in `values` array:

![image](https://user-images.githubusercontent.com/298480/45451843-97c30180-b6dc-11e8-92f8-4e22f14d24fb.png)

Then all of the sudden I see `ADSIGRP_SYM_VALBYHND` to read the value for `bEnable` I guess, not sure where it got index/offset:
![image](https://user-images.githubusercontent.com/298480/45452051-351e3580-b6dd-11e8-8747-9d399dc24902.png)

Then an error:
![image](https://user-images.githubusercontent.com/298480/45452105-5b43d580-b6dd-11e8-9a99-b146bd54f205.png)

Tomorrow I'm going to do `getSymbols`, to see if the index/offset is matching. Second, I'm going to capture the first successful operation and compare.

**Comment by acidos** [comment]
I did a quick capture of successful call and I see `ADSIGRP_SYM_HNDBYNAME`
![image](https://user-images.githubusercontent.com/298480/45452576-a8747700-b6de-11e8-85d1-017a34f061e3.png)

**Comment by ChrisHanuta** [comment]
this is a part of  `var getHandle = function`
```
    if (typeof handle.symhandle === 'undefined') {
      var commandOptions = {
        indexGroup: ADSIGRP.GET_SYMHANDLE_BYNAME,
        indexOffset: 0x00000000,
        writeBuffer: buf,
        readLength: 4,
        symname: handle.symname
      }

      writeReadCommand.call(ads, commandOptions, function (err, result) {
      .....
}
```

plase try only for a test:
```
function WriteAds(client, h)
{
    return new Promise(function(resolve, reject){
        client.write(h, function(err) {
           delete(h.symhandle)
           if (err) 
            {
                reject(err)
            }
            else
            {
                resolve()
            }
        })
    })
}
```

because client.end releases all symhandle you got in the session

```
var end = function (cb) {
 ...
  releaseSymHandles.call(ads, function () {
   ...
```

**Comment by ChrisHanuta** [comment]
> So you mean the old value of synhandle is persisting through the multiple calls?
yes thats javascript

**Comment by ChrisHanuta** [comment]
If I look at the code, it looks like you would pick up a value via http-get and send it to the PLC. 
Ever thought about NODE-RED? 

Timer Node -> HTTP Request Node -> ADS Write Node

**Comment by acidos** [comment]
> Did you slove the connection problem on the localhost?

I'll update previous topic in a moment

**Comment by acidos** [comment]
> 
> 
> If I look at the code, it looks like you would pick up a value via http-get and send it to the PLC.
> Ever thought about NODE-RED?
> 
> Timer Node -> HTTP Request Node -> ADS Write Node

My web request is pretty complex and requires login, cookies, cheerio, header case normalization to extract data. The function is already there(around 200 lines of code) and I'm not sure if I can easily do it with HTTP Request Node.

Also for ADS I need to write float values, extracted from the web, then at the end put validity flag, before invalidation timer expires in PLC. Not sure if this can be achieved in NR as flexible as I do it in single js file.

Currently I installed it as windows service, using node-windows and it's running smoothly. Thanks to you, the problem with symbol not found solved (though I think lib should not keep the state in user object).

With that said, I love NR and always looking for opportunities to use it. But for this task it feels like shooting bird with canon.

**Comment by ChrisHanuta** [comment]
> Thanks to you, the problem with symbol not found solved

Added note in the readme.md
@roccomuso please close

**Comment by roccomuso** [comment]
ok thanks!
