### ISSUE TITLE
Couldn't read array values from beckhoff machines 

### ISSUE THREAD

**Issue by adhavann** [roccomuso/node-ads#2]
Hi @roccomuso ,

I'm trying to use node-ads to read values from beckhoff machine but I couldn't able to read array values , it gives me only the value at position 0, in the array (only displays var[0]).

**Comment by roccomuso** [comment]
did you solve the issue?

**Comment by adhavann** [comment]
Yes . I could solve this one by increasing the bytelength equal to the size of the buffer . 
Thanks
