### ISSUE TITLE
Couldn't write array to beckhoff machines.

### ISSUE THREAD

**Issue by Jasper-Jian** [roccomuso/node-ads#25]
Hi @PLCHome ,
I was trying to use the the write array handle to pass the array to the beckhoff machine. 
But when I pass the array I got an exception of 'Property value not available on handle!'
Here is the handle that I pass through:
var myHandle = {
    symname: 'LLC.arrayOperationToolId',  
    bytelength: ads.array(ads.INT,0,9), 
    value: [0,1,2,3,4,5,6,7,8],
    propname: 'value'
}
The low index and high index is the same register in the twincat and the name is the same as well. 
Other than array everything works fine.
Did I do something wrong?

**Comment by Jasper-Jian** [comment]
fixed by comment out the exception

**Comment by PLCHome** [comment]
ads.array(ads.INT,0,9)
is an Array from 0 to 9 this have 10 values so it must be value: [0,1,2,3,4,5,6,7,8**,9**], and it works!
by LLC.arrayOperationToolId[0..9]
you have:
LLC.arrayOperationToolId[0]=0
LLC.arrayOperationToolId[1]=1
LLC.arrayOperationToolId[2]=2
LLC.arrayOperationToolId[3]=3
LLC.arrayOperationToolId[4]=4
LLC.arrayOperationToolId[5]=5
LLC.arrayOperationToolId[6]=6
LLC.arrayOperationToolId[7]=7
LLC.arrayOperationToolId[8]=8
LLC.arrayOperationToolId[9]=9
