### ISSUE TITLE
use multi read

### ISSUE THREAD

**Issue by heleon19** [roccomuso/node-ads#3]
Hi
How can I use the multi read function? Tried to pass the handle as array, but didn't work.
Thank's for your advice.
Regards Heleon

**Comment by roccomuso** [comment]
Please paste the whole code

**Comment by roccomuso** [comment]
The example is good. Try to put this listeners to catch errors:

```javascript
client.on('notification', function(handle){
    console.log(handle)
})

client.on('error', function(error) {
    console.log(error)
})
```

**Comment by ChrisHanuta** [comment]
@roccomuso it should work properly with 1.4.3
