### ISSUE TITLE
Read / Write / Notify on Index Group / Offset

### ISSUE THREAD

**Issue by Wafje** [roccomuso/node-ads#32]
It would be nice to be able to create a handle using an index group and offset.

For example:
When connecting to port 100 (logger), you can do an Add Device Notification on 0x1 / 0xffff to get notifications of the ADSLOGSTR(), the ones that are normally logged to the event viewer.

**Comment by AuspeXeu** [comment]
You cannot simply create a handle as such?
```
const handle = {
    bytelength: ads.DWORD,
    indexGroup: 0xF020,
    indexOffset: 17
  }
```

**Comment by AuspeXeu** [comment]
Nevermind ... I just realised you cannot do this actually because the `indexOffset` will be overwritten by the code internally.
