### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by sanderd17** [roccomuso/node-ads#4]
When I tried notifications, I could read the value with a handle, but I was never notified of changes.

Apparently, at line 198, there's a condition that never gets satisfied for notifications:

```js
if (ads.pending[invokeId]) {
```

It isn't invoked from the library, so there's no pending object and no callback.

Adding these two lines made the notifications work.
```js
  if (commandId == ID_NOTIFICATION) {
	getNotificationResult.call(this, data)
  } else if (ads.pending[invokeId]) //...
```

Some additional cleanup (like the removing the case and check referencing `ID_NOTIFICATION`) might be needed.

**Comment by roccomuso** [comment]
Would you mind open a PR?

thanks
