### ISSUE TITLE
Does this work on non windows machine?

### ISSUE THREAD

**Issue by simonhoss** [roccomuso/node-ads#40]
Hi

Maybe a stupid question. Can this module work on a non windows machine? Can it directly connect to Beckhoff ADS server?

Thank you in advance

**Comment by PLCHome** [comment]
Yes it can.
If you do everything right.
It just doesn't work well with twincat on Windows. Better under Linux.

I can recommend this to test it: https://flows.nodered.org/node/node-red-contrib-ads

**Comment by simonhoss** [comment]
Nice. I will give it a try.

In the past I always thought the ADS Runtime is needed to make a connection to Beckhoff ADS server. Found here: [https://www.beckhoff.ch/default.asp?download/tc3-download-xar.htm](https://www.beckhoff.ch/default.asp?download/tc3-download-xar.htm)

Did you reimplement this runtime?

**Comment by PLCHome** [comment]
The ADS runtime is another possibility to communicate with the PLC. 
**This implementation speaks natively ADS over TCPIP.** 
If the ADS runtime and this are used together on the same PC, problems can arise.

That's what it does:
https://infosys.beckhoff.com/index.php?content=../content/1031/tcadsamsspec/html/tcadsamsspec_intro.htm&id=572989895309214373

https://infosys.beckhoff.com/index.php?content=../content/1031/tcadsamsspec/html/tcadsamsspec_amstcppackage.htm&id=127006483458795546

**Comment by simonhoss** [comment]
Nice. Thank you. 

Btw. for me the communication worked from a mac. Well Done!
